version: '3.8'
volumes:
  node_modules:

services:
  server:
    build:
      context: .
      target: development
    ports:
      - ${HOST_PORT:-33380}:${SERVER_PORT:-80}
    environment:
      SERVER_PORT: ${SERVER_PORT:-80}
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
